server:
  port: 8080

spring:
  application:
    name: identity-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: INFO
    com.tfm.bandas.identity: DEBUG

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: ${KEYCLOAK_REALM}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
  permitted-roles: ${KEYCLOAK_PERMITTED_ROLES}